-- Flyway baseline for a fresh CityTrip MySQL schema.
-- Existing development databases use baseline-on-migrate and keep historical SQL files under backend/sql.

CREATE TABLE IF NOT EXISTS `trip_user` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(64) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `password_salt` VARCHAR(64) NOT NULL,
  `nickname` VARCHAR(64) NOT NULL,
  `role` TINYINT(1) NOT NULL DEFAULT 0,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `avatar` VARCHAR(255) NULL,
  `gender` TINYINT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_trip_user_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `poi` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(120) NOT NULL,
  `category` VARCHAR(64) NOT NULL,
  `district` VARCHAR(64) NULL,
  `address` VARCHAR(255) NULL,
  `latitude` DECIMAL(10,6) NULL,
  `longitude` DECIMAL(10,6) NULL,
  `open_time` TIME NULL,
  `close_time` TIME NULL,
  `closed_weekdays` VARCHAR(100) NULL,
  `temporarily_closed` TINYINT(1) NOT NULL DEFAULT 0,
  `status_note` VARCHAR(255) NULL,
  `status_source` VARCHAR(50) NOT NULL DEFAULT 'seed',
  `status_updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `avg_cost` DECIMAL(10,2) DEFAULT 0.00,
  `stay_duration` INT NOT NULL DEFAULT 90,
  `indoor` TINYINT(1) DEFAULT 0,
  `night_available` TINYINT(1) DEFAULT 0,
  `rain_friendly` TINYINT(1) DEFAULT 0,
  `walking_level` VARCHAR(20) DEFAULT 'medium',
  `tags` VARCHAR(255) NULL,
  `suitable_for` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `priority_score` DECIMAL(4,2) DEFAULT 3.00,
  `crowd_penalty` DECIMAL(6,2) DEFAULT 0.00,
  `city_code` VARCHAR(16) NULL,
  `city_name` VARCHAR(64) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` BIGINT NULL,
  `updated_by` BIGINT NULL,
  KEY `idx_poi_category` (`category`),
  KEY `idx_poi_city` (`city_code`, `city_name`),
  KEY `idx_poi_status` (`temporarily_closed`, `status_updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `saved_itinerary` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `user_id` BIGINT NOT NULL,
  `request_json` LONGTEXT NOT NULL,
  `itinerary_json` LONGTEXT NOT NULL,
  `custom_title` VARCHAR(120) NULL,
  `share_note` VARCHAR(300) NULL,
  `is_public` TINYINT(1) NOT NULL DEFAULT 0,
  `is_favorite` TINYINT(1) NOT NULL DEFAULT 0,
  `favorited` TINYINT(1) NOT NULL DEFAULT 0,
  `favorite_time` DATETIME NULL,
  `is_history` TINYINT(1) NOT NULL DEFAULT 1,
  `source_page` VARCHAR(50) NULL,
  `node_count` INT NOT NULL DEFAULT 0,
  `total_duration` INT NULL,
  `total_cost` DECIMAL(10,2) NULL,
  `route_signature` VARCHAR(255) NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` BIGINT NULL,
  `is_global_pinned` TINYINT(1) NOT NULL DEFAULT 0,
  `global_pinned_at` DATETIME NULL,
  `global_pinned_by` BIGINT NULL,
  `pinned_comment_id` BIGINT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_saved_itinerary_user` (`user_id`),
  KEY `idx_saved_itinerary_public_deleted_updated` (`is_public`, `is_deleted`, `update_time`),
  KEY `idx_saved_itinerary_global_pinned` (`is_global_pinned`, `global_pinned_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `community_comment` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `itinerary_id` BIGINT NOT NULL,
  `parent_id` BIGINT NULL,
  `user_id` BIGINT NOT NULL,
  `content` VARCHAR(1000) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_community_comment_itinerary` (`itinerary_id`),
  KEY `idx_community_comment_parent` (`parent_id`),
  KEY `idx_community_comment_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `community_like` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `itinerary_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_community_like_user_itinerary` (`itinerary_id`, `user_id`),
  KEY `idx_community_like_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `user_custom_poi` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `user_id` BIGINT NOT NULL,
  `city_name` VARCHAR(64) NULL,
  `name` VARCHAR(120) NOT NULL,
  `rough_location` VARCHAR(255) NOT NULL,
  `category` VARCHAR(64) NULL,
  `reason` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `district` VARCHAR(64) NULL,
  `latitude` DECIMAL(10,6) NULL,
  `longitude` DECIMAL(10,6) NULL,
  `suggested_stay_duration` INT NULL,
  `geo_source` VARCHAR(64) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_user_custom_poi_user` (`user_id`),
  KEY `idx_user_custom_poi_city` (`city_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `saved_itinerary_edit_version` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `itinerary_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `version_no` INT NOT NULL,
  `active_flag` TINYINT(1) NOT NULL DEFAULT 0,
  `source` VARCHAR(32) NOT NULL,
  `summary` VARCHAR(255) NULL,
  `request_json` LONGTEXT NOT NULL,
  `itinerary_json` LONGTEXT NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_itinerary_version_no` (`itinerary_id`, `version_no`),
  KEY `idx_saved_itinerary_edit_version_user` (`user_id`),
  KEY `idx_saved_itinerary_edit_version_active` (`itinerary_id`, `active_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `user_behavior_event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` BIGINT NULL,
  `session_id` VARCHAR(64) NULL,
  `request_id` VARCHAR(64) NULL,
  `event_type` VARCHAR(64) NOT NULL,
  `event_source` VARCHAR(32) NOT NULL DEFAULT 'backend',
  `itinerary_id` BIGINT NULL,
  `poi_id` BIGINT NULL,
  `option_key` VARCHAR(64) NULL,
  `interaction_weight` DECIMAL(8,2) NOT NULL DEFAULT 1.00,
  `success_flag` TINYINT(1) NOT NULL DEFAULT 1,
  `cost_ms` INT NULL,
  `request_uri` VARCHAR(255) NULL,
  `http_method` VARCHAR(16) NULL,
  `client_ip` VARCHAR(64) NULL,
  `user_agent` VARCHAR(255) NULL,
  `referer` VARCHAR(255) NULL,
  `extra_json` LONGTEXT NULL,
  `event_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY `idx_user_behavior_user_time` (`user_id`, `event_time`),
  KEY `idx_user_behavior_event_type_time` (`event_type`, `event_time`),
  KEY `idx_user_behavior_itinerary_time` (`itinerary_id`, `event_time`),
  KEY `idx_user_behavior_poi_time` (`poi_id`, `event_time`),
  KEY `idx_user_behavior_session_time` (`session_id`, `event_time`),
  KEY `idx_user_behavior_request_id` (`request_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `route_plan_fact` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` BIGINT NULL,
  `itinerary_id` BIGINT NULL,
  `plan_source` VARCHAR(32) NOT NULL,
  `algorithm_version` VARCHAR(64) NOT NULL,
  `recall_strategy` VARCHAR(64) NULL,
  `raw_candidate_count` INT NOT NULL DEFAULT 0,
  `filtered_candidate_count` INT NOT NULL DEFAULT 0,
  `final_candidate_count` INT NOT NULL DEFAULT 0,
  `max_stops` INT NOT NULL DEFAULT 0,
  `generated_route_count` INT NOT NULL DEFAULT 0,
  `displayed_option_count` INT NOT NULL DEFAULT 0,
  `selected_option_key` VARCHAR(64) NULL,
  `selected_route_signature` VARCHAR(255) NULL,
  `total_duration` INT NULL,
  `total_cost` DECIMAL(10,2) NULL,
  `total_travel_time` INT NULL,
  `business_risk_score` INT NULL,
  `theme_match_count` INT NULL,
  `route_utility` DECIMAL(12,4) NULL,
  `trip_date` DATE NULL,
  `trip_start_time` TIME NULL,
  `trip_end_time` TIME NULL,
  `budget_level` VARCHAR(20) NULL,
  `is_rainy` TINYINT(1) NOT NULL DEFAULT 0,
  `is_night` TINYINT(1) NOT NULL DEFAULT 0,
  `walking_level` VARCHAR(20) NULL,
  `companion_type` VARCHAR(50) NULL,
  `themes_json` LONGTEXT NULL,
  `request_snapshot_json` LONGTEXT NULL,
  `replan_from_itinerary_id` BIGINT NULL,
  `replace_target_poi_id` BIGINT NULL,
  `replaced_with_poi_id` BIGINT NULL,
  `success_flag` TINYINT(1) NOT NULL DEFAULT 1,
  `fail_reason` VARCHAR(255) NULL,
  `planning_started_at` DATETIME(3) NULL,
  `planning_finished_at` DATETIME(3) NULL,
  `cost_ms` INT NULL,
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY `idx_route_plan_user_time` (`user_id`, `create_time`),
  KEY `idx_route_plan_itinerary` (`itinerary_id`),
  KEY `idx_route_plan_source_time` (`plan_source`, `create_time`),
  KEY `idx_route_plan_trip_date` (`trip_date`),
  KEY `idx_route_plan_success_time` (`success_flag`, `create_time`),
  KEY `idx_route_plan_replace_target` (`replace_target_poi_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `route_node_fact` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `plan_fact_id` BIGINT NOT NULL,
  `itinerary_id` BIGINT NULL,
  `user_id` BIGINT NULL,
  `option_key` VARCHAR(64) NULL,
  `route_signature` VARCHAR(255) NULL,
  `step_order` INT NOT NULL,
  `poi_id` BIGINT NOT NULL,
  `poi_name` VARCHAR(100) NOT NULL,
  `category` VARCHAR(50) NULL,
  `district` VARCHAR(50) NULL,
  `start_time` TIME NULL,
  `end_time` TIME NULL,
  `stay_duration` INT NULL,
  `travel_time` INT NULL,
  `node_cost` DECIMAL(10,2) NULL,
  `sys_reason` VARCHAR(255) NULL,
  `operating_status` VARCHAR(32) NULL,
  `status_note` VARCHAR(255) NULL,
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY `uk_route_node_plan_step` (`plan_fact_id`, `step_order`),
  KEY `idx_route_node_itinerary_step` (`itinerary_id`, `step_order`),
  KEY `idx_route_node_poi_time` (`poi_id`, `create_time`),
  KEY `idx_route_node_user_time` (`user_id`, `create_time`),
  KEY `idx_route_node_option_key` (`option_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
