package com.citytrip.service.domain.scoring;

import com.citytrip.config.AlgorithmWeightsProperties;

public record AlgorithmWeightsSnapshot(double priorityDefaultScore,
                                       double priorityMultiplier,
                                       double localPriorityMultiplier,
                                       double themeMatchScore,
                                       double routeScoreWeight,
                                       double routeTravelPenaltyWeight,
                                       double routeWaitPenaltyWeight,
                                       double routeCrowdPenaltyWeight,
                                       double companionMatchScore,
                                       double groupTravelFitScore,
                                       double groupTravelMismatchPenalty,
                                       double mustVisitScore,
                                       double nightAvailableScore,
                                       double rainFriendlyScore,
                                       double walkingFitScore,
                                       double lowBudgetCheapScore,
                                       double lowBudgetExpensivePenalty,
                                       double lowBudgetMediumPenalty,
                                       double mediumBudgetVeryExpensivePenalty,
                                       double mediumBudgetExpensivePenalty,
                                       double highBudgetPremiumScore,
                                       double statusStalePenalty,
                                       int longStayThresholdMinutes,
                                       double longStayMaxPenalty,
                                       double longStayPenaltyStepMinutes,
                                       double missingBusinessHoursPenalty,
                                       double candidateCrowdScoreWeight,
                                       double minimumPoiScore,
                                       double externalRealtimeBaseBonus,
                                       double externalDataCompletenessBonus,
                                       double externalBusinessDetailsBonus,
                                       double externalBusinessFallbackPenalty,
                                       double firstLegTimePenaltyWeight,
                                       double firstLegDistancePenaltyWeight,
                                       double firstLegTransferPenaltyWeight,
                                       double startModeUnknownPenalty,
                                       double startModeLowWalkingPenalty,
                                       double startModeBikePenalty,
                                       double startModeBusExtraPenalty,
                                       double startModeTaxiExtraPenalty,
                                       double startModeOtherPenalty,
                                       double startDistanceSoftThresholdKm,
                                       double startDistanceSoftThresholdWeight,
                                       double startDistanceMediumThresholdKm,
                                       double startDistanceMediumBasePenalty,
                                       double startDistanceMediumWeight,
                                       double startDistanceHardThresholdKm,
                                       double startDistanceHardBasePenalty,
                                       double startDistanceHardWeight,
                                       int startTimeSoftThresholdMinutes,
                                       double startTimeSoftThresholdWeight,
                                       int startTimeMediumThresholdMinutes,
                                       double startTimeMediumBasePenalty,
                                       double startTimeMediumWeight,
                                       int startTimeHardThresholdMinutes,
                                       double startTimeHardBasePenalty,
                                       double startTimeHardWeight) {

    public static AlgorithmWeightsSnapshot fromProperties(AlgorithmWeightsProperties properties) {
        AlgorithmWeightsProperties source = properties == null ? new AlgorithmWeightsProperties() : properties;
        return new AlgorithmWeightsSnapshot(
                source.getPriorityDefaultScore(),
                source.getPriorityMultiplier(),
                source.getLocalPriorityMultiplier(),
                source.getThemeMatchScore(),
                source.getRouteScoreWeight(),
                source.getRouteTravelPenaltyWeight(),
                source.getRouteWaitPenaltyWeight(),
                source.getRouteCrowdPenaltyWeight(),
                source.getCompanionMatchScore(),
                source.getGroupTravelFitScore(),
                source.getGroupTravelMismatchPenalty(),
                source.getMustVisitScore(),
                source.getNightAvailableScore(),
                source.getRainFriendlyScore(),
                source.getWalkingFitScore(),
                source.getLowBudgetCheapScore(),
                source.getLowBudgetExpensivePenalty(),
                source.getLowBudgetMediumPenalty(),
                source.getMediumBudgetVeryExpensivePenalty(),
                source.getMediumBudgetExpensivePenalty(),
                source.getHighBudgetPremiumScore(),
                source.getStatusStalePenalty(),
                source.getLongStayThresholdMinutes(),
                source.getLongStayMaxPenalty(),
                source.getLongStayPenaltyStepMinutes(),
                source.getMissingBusinessHoursPenalty(),
                source.getCandidateCrowdScoreWeight(),
                source.getMinimumPoiScore(),
                source.getExternalRealtimeBaseBonus(),
                source.getExternalDataCompletenessBonus(),
                source.getExternalBusinessDetailsBonus(),
                source.getExternalBusinessFallbackPenalty(),
                source.getFirstLegTimePenaltyWeight(),
                source.getFirstLegDistancePenaltyWeight(),
                source.getFirstLegTransferPenaltyWeight(),
                source.getStartModeUnknownPenalty(),
                source.getStartModeLowWalkingPenalty(),
                source.getStartModeBikePenalty(),
                source.getStartModeBusExtraPenalty(),
                source.getStartModeTaxiExtraPenalty(),
                source.getStartModeOtherPenalty(),
                source.getStartDistanceSoftThresholdKm(),
                source.getStartDistanceSoftThresholdWeight(),
                source.getStartDistanceMediumThresholdKm(),
                source.getStartDistanceMediumBasePenalty(),
                source.getStartDistanceMediumWeight(),
                source.getStartDistanceHardThresholdKm(),
                source.getStartDistanceHardBasePenalty(),
                source.getStartDistanceHardWeight(),
                source.getStartTimeSoftThresholdMinutes(),
                source.getStartTimeSoftThresholdWeight(),
                source.getStartTimeMediumThresholdMinutes(),
                source.getStartTimeMediumBasePenalty(),
                source.getStartTimeMediumWeight(),
                source.getStartTimeHardThresholdMinutes(),
                source.getStartTimeHardBasePenalty(),
                source.getStartTimeHardWeight()
        );
    }

    public AlgorithmWeightsSnapshot withCompanionMatchScore(double value) {
        return copy(priorityDefaultScore, priorityMultiplier, localPriorityMultiplier, themeMatchScore,
                routeScoreWeight, routeTravelPenaltyWeight, routeWaitPenaltyWeight, routeCrowdPenaltyWeight,
                value, groupTravelFitScore, groupTravelMismatchPenalty, mustVisitScore, nightAvailableScore,
                rainFriendlyScore, walkingFitScore, lowBudgetCheapScore, lowBudgetExpensivePenalty,
                lowBudgetMediumPenalty, mediumBudgetVeryExpensivePenalty, mediumBudgetExpensivePenalty,
                highBudgetPremiumScore, statusStalePenalty, longStayThresholdMinutes, longStayMaxPenalty,
                longStayPenaltyStepMinutes, missingBusinessHoursPenalty, candidateCrowdScoreWeight,
                minimumPoiScore, externalRealtimeBaseBonus, externalDataCompletenessBonus,
                externalBusinessDetailsBonus, externalBusinessFallbackPenalty, firstLegTimePenaltyWeight,
                firstLegDistancePenaltyWeight, firstLegTransferPenaltyWeight, startModeUnknownPenalty,
                startModeLowWalkingPenalty, startModeBikePenalty, startModeBusExtraPenalty,
                startModeTaxiExtraPenalty, startModeOtherPenalty, startDistanceSoftThresholdKm,
                startDistanceSoftThresholdWeight, startDistanceMediumThresholdKm,
                startDistanceMediumBasePenalty, startDistanceMediumWeight, startDistanceHardThresholdKm,
                startDistanceHardBasePenalty, startDistanceHardWeight, startTimeSoftThresholdMinutes,
                startTimeSoftThresholdWeight, startTimeMediumThresholdMinutes, startTimeMediumBasePenalty,
                startTimeMediumWeight, startTimeHardThresholdMinutes, startTimeHardBasePenalty,
                startTimeHardWeight);
    }

    public AlgorithmWeightsSnapshot withRainFriendlyScore(double value) {
        return copy(priorityDefaultScore, priorityMultiplier, localPriorityMultiplier, themeMatchScore,
                routeScoreWeight, routeTravelPenaltyWeight, routeWaitPenaltyWeight, routeCrowdPenaltyWeight,
                companionMatchScore, groupTravelFitScore, groupTravelMismatchPenalty, mustVisitScore,
                nightAvailableScore, value, walkingFitScore, lowBudgetCheapScore, lowBudgetExpensivePenalty,
                lowBudgetMediumPenalty, mediumBudgetVeryExpensivePenalty, mediumBudgetExpensivePenalty,
                highBudgetPremiumScore, statusStalePenalty, longStayThresholdMinutes, longStayMaxPenalty,
                longStayPenaltyStepMinutes, missingBusinessHoursPenalty, candidateCrowdScoreWeight,
                minimumPoiScore, externalRealtimeBaseBonus, externalDataCompletenessBonus,
                externalBusinessDetailsBonus, externalBusinessFallbackPenalty, firstLegTimePenaltyWeight,
                firstLegDistancePenaltyWeight, firstLegTransferPenaltyWeight, startModeUnknownPenalty,
                startModeLowWalkingPenalty, startModeBikePenalty, startModeBusExtraPenalty,
                startModeTaxiExtraPenalty, startModeOtherPenalty, startDistanceSoftThresholdKm,
                startDistanceSoftThresholdWeight, startDistanceMediumThresholdKm,
                startDistanceMediumBasePenalty, startDistanceMediumWeight, startDistanceHardThresholdKm,
                startDistanceHardBasePenalty, startDistanceHardWeight, startTimeSoftThresholdMinutes,
                startTimeSoftThresholdWeight, startTimeMediumThresholdMinutes, startTimeMediumBasePenalty,
                startTimeMediumWeight, startTimeHardThresholdMinutes, startTimeHardBasePenalty,
                startTimeHardWeight);
    }

    public AlgorithmWeightsSnapshot withRouteScoreWeight(double value) {
        return copy(priorityDefaultScore, priorityMultiplier, localPriorityMultiplier, themeMatchScore,
                value, routeTravelPenaltyWeight, routeWaitPenaltyWeight, routeCrowdPenaltyWeight,
                companionMatchScore, groupTravelFitScore, groupTravelMismatchPenalty, mustVisitScore,
                nightAvailableScore, rainFriendlyScore, walkingFitScore, lowBudgetCheapScore,
                lowBudgetExpensivePenalty, lowBudgetMediumPenalty, mediumBudgetVeryExpensivePenalty,
                mediumBudgetExpensivePenalty, highBudgetPremiumScore, statusStalePenalty,
                longStayThresholdMinutes, longStayMaxPenalty, longStayPenaltyStepMinutes,
                missingBusinessHoursPenalty, candidateCrowdScoreWeight, minimumPoiScore,
                externalRealtimeBaseBonus, externalDataCompletenessBonus, externalBusinessDetailsBonus,
                externalBusinessFallbackPenalty, firstLegTimePenaltyWeight, firstLegDistancePenaltyWeight,
                firstLegTransferPenaltyWeight, startModeUnknownPenalty, startModeLowWalkingPenalty,
                startModeBikePenalty, startModeBusExtraPenalty, startModeTaxiExtraPenalty,
                startModeOtherPenalty, startDistanceSoftThresholdKm, startDistanceSoftThresholdWeight,
                startDistanceMediumThresholdKm, startDistanceMediumBasePenalty,
                startDistanceMediumWeight, startDistanceHardThresholdKm, startDistanceHardBasePenalty,
                startDistanceHardWeight, startTimeSoftThresholdMinutes, startTimeSoftThresholdWeight,
                startTimeMediumThresholdMinutes, startTimeMediumBasePenalty, startTimeMediumWeight,
                startTimeHardThresholdMinutes, startTimeHardBasePenalty, startTimeHardWeight);
    }

    private static AlgorithmWeightsSnapshot copy(double priorityDefaultScore,
                                                 double priorityMultiplier,
                                                 double localPriorityMultiplier,
                                                 double themeMatchScore,
                                                 double routeScoreWeight,
                                                 double routeTravelPenaltyWeight,
                                                 double routeWaitPenaltyWeight,
                                                 double routeCrowdPenaltyWeight,
                                                 double companionMatchScore,
                                                 double groupTravelFitScore,
                                                 double groupTravelMismatchPenalty,
                                                 double mustVisitScore,
                                                 double nightAvailableScore,
                                                 double rainFriendlyScore,
                                                 double walkingFitScore,
                                                 double lowBudgetCheapScore,
                                                 double lowBudgetExpensivePenalty,
                                                 double lowBudgetMediumPenalty,
                                                 double mediumBudgetVeryExpensivePenalty,
                                                 double mediumBudgetExpensivePenalty,
                                                 double highBudgetPremiumScore,
                                                 double statusStalePenalty,
                                                 int longStayThresholdMinutes,
                                                 double longStayMaxPenalty,
                                                 double longStayPenaltyStepMinutes,
                                                 double missingBusinessHoursPenalty,
                                                 double candidateCrowdScoreWeight,
                                                 double minimumPoiScore,
                                                 double externalRealtimeBaseBonus,
                                                 double externalDataCompletenessBonus,
                                                 double externalBusinessDetailsBonus,
                                                 double externalBusinessFallbackPenalty,
                                                 double firstLegTimePenaltyWeight,
                                                 double firstLegDistancePenaltyWeight,
                                                 double firstLegTransferPenaltyWeight,
                                                 double startModeUnknownPenalty,
                                                 double startModeLowWalkingPenalty,
                                                 double startModeBikePenalty,
                                                 double startModeBusExtraPenalty,
                                                 double startModeTaxiExtraPenalty,
                                                 double startModeOtherPenalty,
                                                 double startDistanceSoftThresholdKm,
                                                 double startDistanceSoftThresholdWeight,
                                                 double startDistanceMediumThresholdKm,
                                                 double startDistanceMediumBasePenalty,
                                                 double startDistanceMediumWeight,
                                                 double startDistanceHardThresholdKm,
                                                 double startDistanceHardBasePenalty,
                                                 double startDistanceHardWeight,
                                                 int startTimeSoftThresholdMinutes,
                                                 double startTimeSoftThresholdWeight,
                                                 int startTimeMediumThresholdMinutes,
                                                 double startTimeMediumBasePenalty,
                                                 double startTimeMediumWeight,
                                                 int startTimeHardThresholdMinutes,
                                                 double startTimeHardBasePenalty,
                                                 double startTimeHardWeight) {
        return new AlgorithmWeightsSnapshot(priorityDefaultScore, priorityMultiplier, localPriorityMultiplier, themeMatchScore,
                routeScoreWeight, routeTravelPenaltyWeight, routeWaitPenaltyWeight, routeCrowdPenaltyWeight,
                companionMatchScore, groupTravelFitScore, groupTravelMismatchPenalty, mustVisitScore,
                nightAvailableScore, rainFriendlyScore, walkingFitScore, lowBudgetCheapScore,
                lowBudgetExpensivePenalty, lowBudgetMediumPenalty, mediumBudgetVeryExpensivePenalty,
                mediumBudgetExpensivePenalty, highBudgetPremiumScore, statusStalePenalty,
                longStayThresholdMinutes, longStayMaxPenalty, longStayPenaltyStepMinutes,
                missingBusinessHoursPenalty, candidateCrowdScoreWeight, minimumPoiScore,
                externalRealtimeBaseBonus, externalDataCompletenessBonus, externalBusinessDetailsBonus,
                externalBusinessFallbackPenalty, firstLegTimePenaltyWeight, firstLegDistancePenaltyWeight,
                firstLegTransferPenaltyWeight, startModeUnknownPenalty, startModeLowWalkingPenalty,
                startModeBikePenalty, startModeBusExtraPenalty, startModeTaxiExtraPenalty,
                startModeOtherPenalty, startDistanceSoftThresholdKm, startDistanceSoftThresholdWeight,
                startDistanceMediumThresholdKm, startDistanceMediumBasePenalty,
                startDistanceMediumWeight, startDistanceHardThresholdKm, startDistanceHardBasePenalty,
                startDistanceHardWeight, startTimeSoftThresholdMinutes, startTimeSoftThresholdWeight,
                startTimeMediumThresholdMinutes, startTimeMediumBasePenalty, startTimeMediumWeight,
                startTimeHardThresholdMinutes, startTimeHardBasePenalty, startTimeHardWeight);
    }
}